import type { Metadata } from "next";
import { Poppins, Nunito, Montserrat } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/user/navbar/navbar";
import { ToastProvider } from "@/context/toastContext";
import React from "react";
import { useAuth } from "@/authentication/authentication";
import { Suspense } from "react";
import BaseAuth from "./authProviders/baseAuth";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
  display: "swap",
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-nunito",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bluepen",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logo/bluepenonly.svg",
  },
};

export default function RootLayout({
  children,
  login,
}: Readonly<{
  children: React.ReactNode;
  login: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.variable} ${nunito.variable} ${montserrat.variable}`}
    >
      <meta name="referrer" content="strict-origin-when-cross-origin" />
      <meta
        name="google-signin-client_id"
        content="103240549634-39rb11389ceal1dstgkp00pvgfk30iu2.apps.googleusercontent.com"
      />
      <body style={{ fontFamily: "var(--font-poppins), sans-serif" }}>
        <ToastProvider>
          <script
            src="https://accounts.google.com/gsi/client"
            async
            defer
          ></script>
          <div className="fixed">{/* <Navbar></Navbar> */}</div>
          <Suspense
            fallback={
              <div
                className="loading-screen"
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  height: "100vh",
                }}
              >
                <img
                  src="/assets/logo/bluepenLogo.webp"
                  alt="Bluepen Logo"
                  className="logo"
                />
              </div>
            }
          >
            {children}
            {login}
            <BaseAuth />
          </Suspense>
        </ToastProvider>
      </body>
    </html>
  );
}
